version: "3"
services:
  kinkysite:
    build:
      context: .
      dockerfile: DockerfileSymfo
    volumes:
      - ./app/:/var/www/html
    depends_on:
      - bdd
    ports:
      - "80:80"
    networks:
      - kinkynet
  bdd:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3307:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    networks:
      - kinkynet
  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile-phpmyadmin
    environment:
      - "PMA_HOST: mysql"
      - "PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3305:80"
    networks:
      - kinkynet


networks:
  kinkynet:


