version: "3"
services:
  kinkysite:
    build:
      context: .
      dockerfile: DockerfileSymfo
    volumes:
      - ./app:/var/www/html
      - .:/app:cached
      - ./app/var:/symfony/var
      - ./app/vendor:/symfony/vendor
    depends_on:
      - bdd
    ports:
      - "80:80"
    networks:
      - kinkynet
  bdd:
    image: mysql:8
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=hermasite"
      - "MYSQL_user=hermasite"
      - "MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    restart: always
    networks:
      - kinkynet



networks:
  kinkynet:


